version: "3.8"

services:
  db:
    container_name: Paytm
    image: postgres:16
    restart: always
    ports:
      - "5432:5432" # Standard PostgreSQL port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: Paytm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
